"""Cross-module standard-library-only collector budgets."""

MAX_RAW_ZIP_MEMBERS = 512
RAW_CONTROL_MEMBERS = 2
MAX_RAW_SOURCE_MEMBERS = MAX_RAW_ZIP_MEMBERS - RAW_CONTROL_MEMBERS
MAX_RAW_DIRECTORIES = 512
MAX_RAW_DEPTH = 16
